### ISSUE TITLE
output

### ISSUE THREAD

**Issue by dcjohnson23** [getovahit/PRS-Calibration#1]
Hi, I had the following issue ?? on running your script ? Do have a suggestion I could try, many thanks

(PRS_ad) bash-4.2$ python prs-ancestry-calibration.py
Traceback (most recent call last):
  File "prs-ancestry-calibration.py", line 90, in <module>
    main()
  File "prs-ancestry-calibration.py", line 81, in main
    prs_calibrator.fit(prs, pcs)
  File "prs-ancestry-calibration.py", line 34, in fit
    pcs_scaled = self.scaler.fit_transform(pcs)
  File "/.../djohnson/.conda/envs/PRS_ad/lib/python3.7/site-packages/sklearn/base.py", line 852, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/.../djohnson/.conda/envs/PRS_ad/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 806, in fit
    return self.partial_fit(X, y, sample_weight)
  File "/.../djohnson/.conda/envs/PRS_ad/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 847, in partial_fit
    reset=first_call,
  File "/.../djohnson/.conda/envs/PRS_ad/lib/python3.7/site-packages/sklearn/base.py", line 566, in _validate_data
    X = check_array(X, **check_params)
  File "/.../djohnson/.conda/envs/PRS_ad/lib/python3.7/site-packages/sklearn/utils/validation.py", line 746, in check_array
    array = np.asarray(array, order=order, dtype=dtype)
'ValueError: could not convert string to float: 'SAMPLE1''

**Comment by dcjohnson23** [comment]
Thanks for the quick update !! Unfortunately I still encounter an issue:

(venv) bash-4.2$ python prs-ancestry-calibration.py
Traceback (most recent call last):
  File "/homes/homedirs-SCD_genetics_data/sghms/shares/SCD_genetics_data/DavidJ/Projects/AjmalineGWAS/MTAG_PRS/Ancestry.Adjustment/prs-ancestry-calibration.py", line 100, in <module>
    main()
  File "/homes/homedirs-SCD_genetics_data/sghms/shares/SCD_genetics_data/DavidJ/Projects/AjmalineGWAS/MTAG_PRS/Ancestry.Adjustment/prs-ancestry-calibration.py", line 93, in main
    'sample_id': merged_data['sample_id'],
                 ^^^^^^^^^^^
NameError: name 'merged_data' is not defined

**Comment by getovahit** [comment]
script is still a work in progress but I made some changes. give it a try and tell me if it works etc. I updated the readme file for it as well

**Comment by getovahit** [comment]
we did final testing and final code changes and updated both the script and the readme to reflect changes. We now know it works for us. Try the newest versions out and see what happens but at this point I am confident the script works. Check readme as we changed how it runs etc

**Comment by dcjohnson23** [comment]
Cheers...works for me now !
